version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    target_branch: "dev"
    update_schedule: "live"

  - package_manager: "javascript"
    directory: "/"
    target_branch: "dev"
    update_schedule: "live"

  - package_manager: "docker"
    directory: "/"
    target_branch: "dev"
    update_schedule: "weekly"
<<<<<<< HEAD

=======
>>>>>>> ca8a7a4db488a39dff8ba81dc1520de7048a1be4
